apiVersion: tenancy.kflex.kubestellar.org/v1alpha1
kind: ControlPlane
metadata:
  labels:
    app.kubernetes.io/name: controlplane
    app.kubernetes.io/instance: controlplane-sample
    app.kubernetes.io/part-of: kubeflex
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: kubeflex
  name: cp1
spec:
  type: k8s
  backend: shared
